services:
    _defaults:
        autowire: true
        public: true

    netosoft_domain.chain_handler:
        class: Netosoft\DomainBundle\Domain\ChainHandler

    netosoft_domain.handler:
        class: Netosoft\DomainBundle\Domain\LogHandler
        arguments:
            0: "@doctrine.orm.log_handler_entity_manager"
            1: "@monolog.logger.command_log"
        calls:
            - ['setDecoratedHandler', ['@netosoft_domain.chain_handler']]

    Netosoft\DomainBundle\Domain\HandlerInterface:
        alias: netosoft_domain.handler

    netosoft_domain.handler_configurator:
        class: Netosoft\DomainBundle\Domain\HandlerConfigurator

    Netosoft\DomainBundle\Domain\Logger\CommandLogger:
        autowire: true
        arguments:
            - "@service_container"
            - "@annotations.reader"
            - "@netosoft_domain.default_command_logger"

    netosoft_domain.original_default_command_logger:
        class: Netosoft\DomainBundle\Domain\Logger\DefaultCommandLogger

    Netosoft\DomainBundle\Domain\Logger\NoneLogger: ~
    netosoft_domain.none_logger:
        alias: Netosoft\DomainBundle\Domain\Logger\NoneLogger

    Netosoft\DomainBundle\Domain\Utils\LoggerUtils:
        public: false
        autowire: true
        arguments:
            0: "@netosoft_domain.cache_logger_utils"

    Netosoft\DomainBundle\Domain\Utils\SecurityUtils:
        public: false

    Netosoft\DomainBundle\Domain\Utils\ValidatorUtils:
        public: false

    Netosoft\DomainBundle\Domain\Handler\EditFieldHandler:
        public: false
        arguments:
            0: "@doctrine.orm.default_entity_manager"
        tags:
            - {name: "netosoft_domain.handler"}

    Netosoft\DomainBundle\Action\ActionHelper:
        arguments:
            $breadcrumbsBuilder: "@sonata.admin.breadcrumbs_builder"
            $session: "@session"


    Netosoft\DomainBundle\Form\Type\SelectCommandLogCommandClassType:
        tags:
            - {name: form.type}

    Netosoft\DomainBundle\Form\Type\SelectCommandLogTypeType:
        tags:
            - {name: form.type}

    Netosoft\DomainBundle\Action\ResolverHelper: ~
    Netosoft\DomainBundle\Action\AdminCommandFormAction: ~
    Netosoft\DomainBundle\Action\BaseCommandFormAction: ~
    Netosoft\DomainBundle\Action\DeleteAction: ~
    Netosoft\DomainBundle\Action\EditFieldFormAction: ~
    Netosoft\DomainBundle\Action\RenderFieldListAction: ~
    Netosoft\DomainBundle\Action\RenderRowAction: ~
    Netosoft\DomainBundle\Domain\Handler\HandlerHelper: ~

    Netosoft\DomainBundle\Domain\Logger\ExpressionLanguageProvider: ~